In [1]:
import numpy as np

In [2]:
# Creating an array 
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape
# Will return the n rows and m columns (n,m)

(3, 5)

In [5]:
a.dtype.name
# Will return the dtype. Ex: int32, int16, float64 

'int32'

In [6]:
a.size
# Will return total elements in the array. Basically n*m

15

In [8]:
# Array Creation
# There are several ways to create arrays.
# 1. By Python Lists
b = np.array([3,7,9,2])
b

array([3, 7, 9, 2])

In [9]:
# 2. By Tuple
c = np.array((2,6,8,3))
c

array([2, 6, 8, 3])

In [13]:
# If passed many sequences it will convert into two-dimensional and three-dimensional
two_d_arr = np.array([(1,2,6), (7,9,3)])
two_d_arr

array([[1, 2, 6],
       [7, 9, 3]])

In [14]:
three_d_arr = np.array([(2,3,7), (4,2,8), (9,3,2)])
three_d_arr

array([[2, 3, 7],
       [4, 2, 8],
       [9, 3, 2]])

In [15]:
# 3. From function zeroes. It will create an array full of zeroes
zer_arr = np.zeros((3,4))
zer_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# 4. From function ones. It will create an array full of ones.
one_arr = np.ones((3,4))
one_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# 5. From arange function.
# It use to create sequences of numbers. Works same as Python built-in range function.
arange_arr = np.arange(1,10)
arange_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
another_arange_arr = np.arange(2.4, 8.2, 0.2)
another_arange_arr

array([2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8,
       5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4,
       7.6, 7.8, 8. ])

In [23]:
# When arange is used with floating point arguments,
# it is generally not possible to predict the number of elemnts obtained, due to the finite floating point precision.
# For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want,
# instead of the step.
ln_space_arr = np.linspace(0,2,9)
ln_space_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])